<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arduino" nsURI="http://www.example.org/arduino" nsPrefix="arduino">
  <eClassifiers xsi:type="ecore:EClass" name="Sketch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensores" upperBound="-1"
        eType="#//Sensores" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuadores" upperBound="-1"
        eType="#//Actuadores" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instrucciones" upperBound="-1"
        eType="#//Instrucciones" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuadores" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruccionactuador" eType="#//Instrucciones"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensores" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="med" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="act" upperBound="12" eType="#//Actuadores"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Led" eSuperTypes="#//Actuadores"/>
  <eClassifiers xsi:type="ecore:EClass" name="LDR" eSuperTypes="#//Sensores"/>
  <eClassifiers xsi:type="ecore:EClass" name="Instrucciones" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Apagar" eSuperTypes="#//Instrucciones"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variar" eSuperTypes="#//Instrucciones">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pwm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datos" eType="#//Sensores"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Esperar" eSuperTypes="#//Instrucciones">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="segundos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="apagar" eType="#//Apagar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Encender" eSuperTypes="#//Instrucciones">
    <eStructuralFeatures xsi:type="ecore:EReference" name="esperar" eType="#//Esperar"/>
  </eClassifiers>
</ecore:EPackage>
